### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by illiaKuryaki** [Hephyrius/binance_futures_bot#22]
Hi, just wanted to test this on binance futures testnet, but i am getting a Invalid Syntax error :

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 462, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 472, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 428, in iter_importers
    __import__(pkg)
  File "bot.py", line 74
    bf.singlePrint(f"Exited Position: {qty} ${market_price}", std)
                                                           ^
SyntaxError: invalid syntax

Python 2.7.16

**Comment by King-fu** [comment]
Hi just start with command: python3 bot.py

**Comment by Hephyrius** [comment]
python3 for linux, or python for windows as long as your path points to a python3 instance

**Comment by illiaKuryaki** [comment]
Rgr, Thanks !
